#!/bin/bash
set -Ceux

# コマンド実行時の第2引数以下をARGに格納
ARG=${@:2}

DC="docker-compose run --rm web"

case ${1} in
  "up" ) ## Rails サーバを起動します
    rm -f ./tmp/pids/server.pid
    docker-compose run --service-ports --rm web bundle exec rails s -b 0.0.0.0;;
  "clean" ) ## web コンテナを削除します
    docker-compose stop
    docker-compose rm -f web;;
  "exec" ) ## bundle exec を実行します
    ${DC} bundle exec ${ARG};;
  "rails" | "rake" | "r" ) ## rails コマンドを実行します
    ${DC} bundle exec rails ${ARG};;
  "bundle" ) ## bundle コマンドを実行します
    ${DC} bundle ${ARG};;
  "test" | "rspec" ) ## rspec コマンドを実行します
    ${DC} bundle exec rspec ${ARG};;
  "setup" ) ## docker-composeで環境構築します
    docker-compose build
    ${DC} bundle install
    ${DC} bundle exec rake db:setup;;
  "help" | * )
    (
      echo "HELP"
      echo "  COMMAND ) DESCRIPTION"
      \grep -E "\)\ *\##" ${0}
    ) | column -t -s "\)"
esac
